export interface Arcane {
  name: string; slug: string; tier: string; motes?: number; syndicate?: string; cost?: number
}

export const ARCANES: Arcane[] = [
  { name: 'Arcane Energize',     slug: 'arcane_energize',     tier: 'Legendary', motes: 30 },
  { name: 'Arcane Grace',        slug: 'arcane_grace',        tier: 'Legendary', motes: 30 },
  { name: 'Arcane Barrier',      slug: 'arcane_barrier',      tier: 'Legendary', motes: 30 },
  { name: 'Arcane Aegis',        slug: 'arcane_aegis',        tier: 'Rare',      motes: 6  },
  { name: 'Arcane Arachne',      slug: 'arcane_arachne',      tier: 'Rare',      motes: 6  },
  { name: 'Arcane Avenger',      slug: 'arcane_avenger',      tier: 'Rare',      motes: 6  },
  { name: 'Arcane Fury',         slug: 'arcane_fury',         tier: 'Rare',      motes: 6  },
  { name: 'Arcane Precision',    slug: 'arcane_precision',    tier: 'Rare',      motes: 6  },
  { name: 'Arcane Pulse',        slug: 'arcane_pulse',        tier: 'Rare',      motes: 6  },
  { name: 'Arcane Rage',         slug: 'arcane_rage',         tier: 'Rare',      motes: 6  },
  { name: 'Arcane Ultimatum',    slug: 'arcane_ultimatum',    tier: 'Rare',      motes: 6  },
  { name: 'Arcane Victory',      slug: 'arcane_victory',      tier: 'Uncommon',  motes: 4  },
  { name: 'Arcane Strike',       slug: 'arcane_strike',       tier: 'Uncommon',  motes: 4  },
  { name: 'Arcane Awakening',    slug: 'arcane_awakening',    tier: 'Uncommon',  motes: 4  },
  { name: 'Arcane Guardian',     slug: 'arcane_guardian',     tier: 'Uncommon',  motes: 4  },
  { name: 'Arcane Phantasm',     slug: 'arcane_phantasm',     tier: 'Uncommon',  motes: 4  },
  { name: 'Arcane Eruption',     slug: 'arcane_eruption',     tier: 'Uncommon',  motes: 4  },
  { name: 'Arcane Agility',      slug: 'arcane_agility',      tier: 'Uncommon',  motes: 4  },
  { name: 'Arcane Acceleration', slug: 'arcane_acceleration', tier: 'Uncommon',  motes: 4  },
  { name: 'Arcane Trickery',     slug: 'arcane_trickery',     tier: 'Uncommon',  motes: 4  },
  { name: 'Arcane Velocity',     slug: 'arcane_velocity',     tier: 'Uncommon',  motes: 4  },
  { name: 'Arcane Deflection',   slug: 'arcane_deflection',   tier: 'Uncommon',  motes: 2  },
  { name: 'Arcane Healing',      slug: 'arcane_healing',      tier: 'Uncommon',  motes: 2  },
  { name: 'Arcane Resistance',   slug: 'arcane_resistance',   tier: 'Uncommon',  motes: 2  },
  { name: 'Arcane Nullifier',    slug: 'arcane_nullifier',    tier: 'Common',    motes: 2  },
  { name: 'Arcane Warmth',       slug: 'arcane_warmth',       tier: 'Common',    motes: 2  },
  { name: 'Arcane Ice',          slug: 'arcane_ice',          tier: 'Common',    motes: 2  },
  { name: 'Arcane Momentum',     slug: 'arcane_momentum',     tier: 'Common',    motes: 2  },
  { name: 'Arcane Tempo',        slug: 'arcane_tempo',        tier: 'Common',    motes: 2  },
  { name: 'Arcane Consequence',  slug: 'arcane_consequence',  tier: 'Common',    motes: 2  },
  { name: 'Arcane Ice Storm',    slug: 'arcane_ice_storm',    tier: 'Ascension', motes: 10 },
  { name: 'Arcane Battery',      slug: 'arcane_battery',      tier: 'Ascension', motes: 10 },
  { name: 'Secondary Surge',     slug: 'secondary_surge',     tier: 'Ascension', motes: 10 },
  { name: 'Secondary Fortifier', slug: 'secondary_fortifier', tier: 'Ascension', motes: 10 },
  { name: 'Melee Afflictions',   slug: 'melee_afflictions',   tier: 'Ascension', motes: 10 },
  { name: 'Secondary Enervate',  slug: 'secondary_enervate',  tier: 'Special'   },
  { name: 'Arcane Crepuscular',  slug: 'arcane_crepuscular',  tier: 'Special'   },
  { name: 'Arcane Truculence',   slug: 'arcane_truculence',   tier: 'Special'   },
  { name: 'Arcane Bellicose',    slug: 'arcane_bellicose',    tier: 'Special'   },
  { name: 'Arcane Camisado',     slug: 'arcane_camisado',     tier: 'Special'   },
  { name: 'Primary Crux',        slug: 'primary_crux',        tier: 'Special'   },
  { name: 'Melee Doughty',       slug: 'melee_doughty',       tier: 'Special'   },
  { name: 'Arcane Impetus',      slug: 'arcane_impetus',      tier: 'Special'   },
  { name: 'Exodia Brave',        slug: 'exodia_brave',        tier: 'Syndicate', syndicate: 'Ostron',         cost: 10000 },
  { name: 'Exodia Force',        slug: 'exodia_force',        tier: 'Syndicate', syndicate: 'Ostron',         cost: 10000 },
  { name: 'Exodia Hunt',         slug: 'exodia_hunt',         tier: 'Syndicate', syndicate: 'Ostron',         cost: 10000 },
  { name: 'Exodia Might',        slug: 'exodia_might',        tier: 'Syndicate', syndicate: 'Ostron',         cost: 10000 },
  { name: 'Exodia Triumph',      slug: 'exodia_triumph',      tier: 'Syndicate', syndicate: 'Ostron',         cost: 10000 },
  { name: 'Exodia Valor',        slug: 'exodia_valor',        tier: 'Syndicate', syndicate: 'Ostron',         cost: 10000 },
  { name: 'Magus Vigor',         slug: 'magus_vigor',         tier: 'Syndicate', syndicate: 'The Quills',     cost: 10000 },
  { name: 'Magus Husk',          slug: 'magus_husk',          tier: 'Syndicate', syndicate: 'The Quills',     cost: 10000 },
  { name: 'Magus Cloud',         slug: 'magus_cloud',         tier: 'Syndicate', syndicate: 'The Quills',     cost: 10000 },
  { name: 'Magus Cadence',       slug: 'magus_cadence',       tier: 'Syndicate', syndicate: 'The Quills',     cost: 10000 },
  { name: 'Magus Replenish',     slug: 'magus_replenish',     tier: 'Syndicate', syndicate: 'The Quills',     cost: 10000 },
  { name: 'Magus Elevate',       slug: 'magus_elevate',       tier: 'Syndicate', syndicate: 'The Quills',     cost: 10000 },
  { name: 'Magus Nourish',       slug: 'magus_nourish',       tier: 'Syndicate', syndicate: 'The Quills',     cost: 10000 },
  { name: 'Virtuos Null',        slug: 'virtuos_null',        tier: 'Syndicate', syndicate: 'The Quills',     cost: 10000 },
  { name: 'Virtuos Tempo',       slug: 'virtuos_tempo',       tier: 'Syndicate', syndicate: 'The Quills',     cost: 10000 },
  { name: 'Virtuos Fury',        slug: 'virtuos_fury',        tier: 'Syndicate', syndicate: 'The Quills',     cost: 10000 },
  { name: 'Virtuos Strike',      slug: 'virtuos_strike',      tier: 'Syndicate', syndicate: 'The Quills',     cost: 10000 },
  { name: 'Virtuos Shadow',      slug: 'virtuos_shadow',      tier: 'Syndicate', syndicate: 'The Quills',     cost: 10000 },
  { name: 'Virtuos Ghost',       slug: 'virtuos_ghost',       tier: 'Syndicate', syndicate: 'The Quills',     cost: 10000 },
  { name: 'Pax Charge',          slug: 'pax_charge',          tier: 'Syndicate', syndicate: 'Solaris United', cost: 10000 },
  { name: 'Pax Soar',            slug: 'pax_soar',            tier: 'Syndicate', syndicate: 'Solaris United', cost: 10000 },
  { name: 'Pax Bolt',            slug: 'pax_bolt',            tier: 'Syndicate', syndicate: 'Solaris United', cost: 10000 },
  { name: 'Pax Seeker',          slug: 'pax_seeker',          tier: 'Syndicate', syndicate: 'Solaris United', cost: 10000 },
  { name: 'Magus Accelerant',    slug: 'magus_accelerant',    tier: 'Syndicate', syndicate: 'Vox Solaris',    cost: 10000 },
  { name: 'Magus Anomaly',       slug: 'magus_anomaly',       tier: 'Syndicate', syndicate: 'Vox Solaris',    cost: 10000 },
  { name: 'Magus Destruct',      slug: 'magus_destruct',      tier: 'Syndicate', syndicate: 'Vox Solaris',    cost: 10000 },
  { name: 'Magus Drive',         slug: 'magus_drive',         tier: 'Syndicate', syndicate: 'Vox Solaris',    cost: 10000 },
  { name: 'Magus Firewall',      slug: 'magus_firewall',      tier: 'Syndicate', syndicate: 'Vox Solaris',    cost: 10000 },
  { name: 'Magus Glitch',        slug: 'magus_glitch',        tier: 'Syndicate', syndicate: 'Vox Solaris',    cost: 10000 },
  { name: 'Magus Lockdown',      slug: 'magus_lockdown',      tier: 'Syndicate', syndicate: 'Vox Solaris',    cost: 10000 },
  { name: 'Magus Melt',          slug: 'magus_melt',          tier: 'Syndicate', syndicate: 'Vox Solaris',    cost: 10000 },
  { name: 'Magus Overload',      slug: 'magus_overload',      tier: 'Syndicate', syndicate: 'Vox Solaris',    cost: 10000 },
  { name: 'Magus Repair',        slug: 'magus_repair',        tier: 'Syndicate', syndicate: 'Vox Solaris',    cost: 10000 },
  { name: 'Magus Revert',        slug: 'magus_revert',        tier: 'Syndicate', syndicate: 'Vox Solaris',    cost: 10000 },
  { name: 'Virtuos Forge',       slug: 'virtuos_forge',       tier: 'Syndicate', syndicate: 'Vox Solaris',    cost: 10000 },
  { name: 'Virtuos Surge',       slug: 'virtuos_surge',       tier: 'Syndicate', syndicate: 'Vox Solaris',    cost: 10000 },
  { name: 'Virtuos Trojan',      slug: 'virtuos_trojan',      tier: 'Syndicate', syndicate: 'Vox Solaris',    cost: 10000 },
  { name: 'Theorem Demulcent',   slug: 'theorem_demulcent',   tier: 'Syndicate', syndicate: 'Entrati',        cost: 2500  },
  { name: 'Theorem Infection',   slug: 'theorem_infection',   tier: 'Syndicate', syndicate: 'Entrati',        cost: 2500  },
  { name: 'Theorem Contagion',   slug: 'theorem_contagion',   tier: 'Syndicate', syndicate: 'Entrati',        cost: 2500  },
  { name: 'Residual Boils',      slug: 'residual_boils',      tier: 'Syndicate', syndicate: 'Entrati',        cost: 2500  },
  { name: 'Residual Malodor',    slug: 'residual_malodor',    tier: 'Syndicate', syndicate: 'Entrati',        cost: 2500  },
  { name: 'Residual Shock',      slug: 'residual_shock',      tier: 'Syndicate', syndicate: 'Entrati',        cost: 2500  },
  { name: 'Residual Viremia',    slug: 'residual_viremia',    tier: 'Syndicate', syndicate: 'Entrati',        cost: 2500  },
  { name: 'Molt Augmented',      slug: 'molt_augmented',      tier: 'Syndicate', syndicate: 'Holdfasts',      cost: 10000 },
  { name: 'Molt Efficiency',     slug: 'molt_efficiency',     tier: 'Syndicate', syndicate: 'Holdfasts',      cost: 10000 },
  { name: 'Molt Reconstruct',    slug: 'molt_reconstruct',    tier: 'Syndicate', syndicate: 'Holdfasts',      cost: 10000 },
  { name: 'Molt Vigor',          slug: 'molt_vigor',          tier: 'Syndicate', syndicate: 'Holdfasts',      cost: 10000 },
  { name: 'Cascadia Accuracy',   slug: 'cascadia_accuracy',   tier: 'Syndicate', syndicate: 'Holdfasts',      cost: 10000 },
  { name: 'Cascadia Empowered',  slug: 'cascadia_empowered',  tier: 'Syndicate', syndicate: 'Holdfasts',      cost: 10000 },
  { name: 'Cascadia Flare',      slug: 'cascadia_flare',      tier: 'Syndicate', syndicate: 'Holdfasts',      cost: 10000 },
  { name: 'Cascadia Overcharge', slug: 'cascadia_overcharge', tier: 'Syndicate', syndicate: 'Holdfasts',      cost: 10000 },
  { name: 'Primary Frostbite',   slug: 'primary_frostbite',   tier: 'Syndicate', syndicate: 'Holdfasts',      cost: 10000 },
  { name: 'Fractalized Reset',   slug: 'fractalized_reset',   tier: 'Syndicate', syndicate: 'Holdfasts',      cost: 10000 },
  { name: 'Emergence Dissipate', slug: 'emergence_dissipate', tier: 'Syndicate', syndicate: 'Holdfasts',      cost: 10000 },
  { name: 'Emergence Renewed',   slug: 'emergence_renewed',   tier: 'Syndicate', syndicate: 'Holdfasts',      cost: 10000 },
  { name: 'Emergence Savior',    slug: 'emergence_savior',    tier: 'Syndicate', syndicate: 'Holdfasts',      cost: 10000 },
  { name: 'Melee Animosity',     slug: 'melee_animosity',     tier: 'Syndicate', syndicate: 'Cavia',          cost: 10000 },
  { name: 'Melee Exposure',      slug: 'melee_exposure',      tier: 'Syndicate', syndicate: 'Cavia',          cost: 10000 },
  { name: 'Melee Fortification', slug: 'melee_fortification', tier: 'Syndicate', syndicate: 'Cavia',          cost: 10000 },
  { name: 'Melee Influence',     slug: 'melee_influence',     tier: 'Syndicate', syndicate: 'Cavia',          cost: 10000 },
  { name: 'Melee Retaliation',   slug: 'melee_retaliation',   tier: 'Syndicate', syndicate: 'Cavia',          cost: 10000 },
  { name: 'Melee Vortex',        slug: 'melee_vortex',        tier: 'Syndicate', syndicate: 'Cavia',          cost: 10000 },
]
